#Andrew Scheel
Assign6 : assign6.o memory.o
	g++ -Wall -o Assign6 assign6.o memory.o

assign6.o : assign6.cpp
	g++ -Wall -c assign6.cpp
memory.o: memory.cpp
	g++ -Wall -c memory.cpp
clean :
	- rm *.o Assign6
